# Generated by Django 2.1.7 on 2019-03-13 04:52


from django.db import migrations
from main.models import Stock
from datetime import datetime
import os
import csv

def loadStocks(apps, schema_editor):

	raw_files_paths = os.listdir("csv")
	for path in raw_files_paths:
		with open("csv/" + path) as f:
			temp_symbol = os.path.splitext(path)[0]
			reader = csv.reader(f)
			for row in reader:
				tempDate = datetime.strptime(row[0], "%d/%m/%Y").date()
				s = Stock(stock_symbol=temp_symbol, close_price=float(row[1]), date=tempDate)
				s.save()
	print("All files loaded.")



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(loadStocks),
    ]